version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "mysite.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
#        max_size: "200k"
    volumes:
      - ./mysite/database:/app/database

#    logging:
#      driver: loki
#      options:
#        loki-url: http://localhost:3100/loki/api/v1/push
#        loki-url: http://host.docker.internal:3100/loki/api/v1/push

#  grafana:
#    image: grafana/grafana:9.2.15
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    ports:
#      - "3000:3000"
#
#  loki:
#    image: grafana/loki:2.8.0
#    ports:
#      - "3100:3100"